// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: learn.proto

package learn

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_learn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{0}
}

func (x *UserRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_learn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_learn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{2}
}

func (x *User) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type GetUsersRsponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRsponse) Reset() {
	*x = GetUsersRsponse{}
	mi := &file_learn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRsponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRsponse) ProtoMessage() {}

func (x *GetUsersRsponse) ProtoReflect() protoreflect.Message {
	mi := &file_learn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRsponse.ProtoReflect.Descriptor instead.
func (*GetUsersRsponse) Descriptor() ([]byte, []int) {
	return file_learn_proto_rawDescGZIP(), []int{3}
}

func (x *GetUsersRsponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_learn_proto protoreflect.FileDescriptor

const file_learn_proto_rawDesc = "" +
	"\n" +
	"\vlearn.proto\"\x1d\n" +
	"\vUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"\x0e\n" +
	"\fEmptyMessage\"<\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\".\n" +
	"\x0fGetUsersRsponse\x12\x1b\n" +
	"\x05users\x18\x01 \x03(\v2\x05.UserR\x05users2\x89\x01\n" +
	"\bHelloApp\x12 \n" +
	"\aGetUser\x12\f.UserRequest\x1a\x05.User\"\x00\x12$\n" +
	"\bGetUsers\x12\r.EmptyMessage\x1a\x05.User\"\x000\x01\x125\n" +
	"\x10GetUsersNoStream\x12\r.EmptyMessage\x1a\x10.GetUsersRsponse\"\x00B\x0eZ\fshared/learnb\x06proto3"

var (
	file_learn_proto_rawDescOnce sync.Once
	file_learn_proto_rawDescData []byte
)

func file_learn_proto_rawDescGZIP() []byte {
	file_learn_proto_rawDescOnce.Do(func() {
		file_learn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)))
	})
	return file_learn_proto_rawDescData
}

var file_learn_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_learn_proto_goTypes = []any{
	(*UserRequest)(nil),     // 0: UserRequest
	(*EmptyMessage)(nil),    // 1: EmptyMessage
	(*User)(nil),            // 2: User
	(*GetUsersRsponse)(nil), // 3: GetUsersRsponse
}
var file_learn_proto_depIdxs = []int32{
	2, // 0: GetUsersRsponse.users:type_name -> User
	0, // 1: HelloApp.GetUser:input_type -> UserRequest
	1, // 2: HelloApp.GetUsers:input_type -> EmptyMessage
	1, // 3: HelloApp.GetUsersNoStream:input_type -> EmptyMessage
	2, // 4: HelloApp.GetUser:output_type -> User
	2, // 5: HelloApp.GetUsers:output_type -> User
	3, // 6: HelloApp.GetUsersNoStream:output_type -> GetUsersRsponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_learn_proto_init() }
func file_learn_proto_init() {
	if File_learn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_learn_proto_rawDesc), len(file_learn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_learn_proto_goTypes,
		DependencyIndexes: file_learn_proto_depIdxs,
		MessageInfos:      file_learn_proto_msgTypes,
	}.Build()
	File_learn_proto = out.File
	file_learn_proto_goTypes = nil
	file_learn_proto_depIdxs = nil
}
